name: taxi_app
description: A taxi emergency app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Packages
  socket_io_client: ^2.0.0
  http: ^0.13.5
  google_sign_in: ^5.4.0
  flutter_facebook_auth: ^5.0.11
  sign_in_with_apple: ^3.2.0
  geolocator: ^9.0.2
  flutter_local_notifications: ^16.3.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  image_picker: ^0.8.7+5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
